### ISSUE TITLE
integrate, document, and test the osm2pgsql --sanitize-columns patch

### ISSUE THREAD

**Issue by springmeyer** [hotosm/hotosm-system-admin#3]
@schuyler implemented a patch to osm2pgsql [here](https://github.com/schuyler/osm2pgsql/commit/970ca5f7204d65b634545cec2aac9f9bea27e7) that allows for columns to be sanitized so that fields will not contain characters that require quoting. The motivation for this work was that programs like ArcGIS are not smart enough to quote fields and many common operations to query data will therefore fail.

Tasks:

1) Integrate this patch upstream into osm2pgsql svn
2) Document the `--sanitize-columns` usage on the [OSM wiki](http://wiki.openstreetmap.org/wiki/Osm2pgsql)
3) Test and import and run through procedure with ArcGIS to ensure things work better.

/cc @schuyler  - can you integrate upstream?

/cc @manelclos - you graciously helped test this before - would you be able to run through #3 with this modified code?

**Comment by stefanocudini** [comment]
*--sanitize-columns* doesn't exist anymore?
