### ISSUE TITLE
Images not uploading

### ISSUE THREAD

**Issue by smit1678** [hotosm/hotosm-system-admin#88]
On the staging hotosm.org site, when adding a new Update I'm getting the following error when attempting to upload a file: 

> The file could not be uploaded.

The file was previously uploaded on the production site for a blog post and is under 2mb, so it should work correctly.

**Comment by davidneudorfer** [comment]
Image uploads work now but thumbnail previews are still broken.

![image](https://cloud.githubusercontent.com/assets/547876/23693200/1e3cd588-0388-11e7-8677-acaed827e618.png)

**Comment by davidneudorfer** [comment]
This is resolved. 
![image](https://cloud.githubusercontent.com/assets/547876/23696008/b1a18d56-0396-11e7-8f69-0f7dd258c3e2.png)
